id: P007977
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20664
  title: ཀི་ལྭེན་བྱིས་སྒྲུང་།
  author: ''
  volumes:
    fcea355570794570b02d1f93acfb99b3:
      image_group_id: I8LS20666
      title: ''
      volume_number: 1
      total_pages: 222
ebook_metadata:
  title: ཀི་ལྭེན་བྱིས་སྒྲུང་།
  author: ''
  sku: P007977
  cover: cover.jpg
  layers:
  - pagination
