id: P007977
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20664
  title: ཀི་ལྭེན་བྱིས་སྒྲུང་།
  author: ''
  volumes:
    c469abcd82e34c2384a08c9bf4d59502:
      image_group_id: I8LS20666
      title: Volume 1 of ki l+'en byis sgrung /
      volume_number: 1
      total_pages: 222
      base_file: v001.txt
ebook_metadata:
  title: ཀི་ལྭེན་བྱིས་སྒྲུང་།
  author: ''
  sku: P007977
  cover: cover.jpg
  layers:
  - pagination
